#ifndef DART_RENDER_CONFIGS_H_
#define DART_RENDER_CONFIGS_H_

#include <stdlib.h>
#include <vector>
#include <string>

std::string dart_header = "/// GENERATED BY terra, DO NOT MODIFY BY HAND.\n\n// ignore_for_file: public_member_api_docs, unused_local_variable, unused_import";

std::vector<std::string> event_handler_class_{
    "agora::rtc::IRtcEngineEventHandler",
    "agora::rtc::IRtcEngineEventHandlerEx",
    "agora::base::LicenseCallback",
    "agora::rtc::IAudioEncodedFrameObserver",
    "agora::rtc::IVideoEncodedImageReceiver",
    "agora::rtc::IPacketObserver",
    "agora::media::IAudioSpectrumObserver",
    "agora::media::IVideoEncodedFrameObserver",
    "agora::media::ISnapshotCallback",
    "agora::rtc::IMediaStreamingSourceObserver",
    "agora::rtc::IMetadataObserver",
    "agora::rtc::IMediaPlayerSourceObserver",
    "agora::rtc::IDirectCdnStreamingEventHandler",
    "agora::media::IAudioFrameObserver",
    "agora::media::IVideoFrameObserver",
    "agora::media::IMediaRecorderObserver",
    "agora::media::IAudioFrameObserverBase",
    "agora::rtc::ext::IMediaPlayerAudioFrameObserver",
    "agora::rtc::ext::IMediaPlayerVideoFrameObserver",
    "agora::media::IAudioPcmFrameSink",
    "agora::rtc::IMusicContentCenterEventHandler",
    "agora::rtc::IH265TranscoderObserver",
    "agora::rtm::IRtmEventHandler",
};

std::vector<std::string> filter_event_handler_prefix_class_{
    // "agora::rtc::IRtcEngineEventHandler",
    "agora::rtc::IRtcEngineEventHandlerEx",
};

std::vector<std::string> IgnoreJsonType{"Uint8List", "RtmEventHandler"};

std::vector<std::string> IgnoreBufferExtType{"RtmEventHandler"};

std::vector<std::string> IgnoreJsonClass{"agora::rtc::LocalSpatialAudioConfig"};

std::vector<std::string> IgnoreDartStyleType{"agora::rtc::SIZE"};

std::vector<std::string> donot_trim_prefix_i_class_{
    "agora::rtc::InjectStreamConfig",
    "agora::rtc::ImageTrackOptions",
};

std::map<std::string, std::vector<std::string>> synchronized_functions_ = {
    {
        "agora::rtc::IRtcEngine",
        {
            "registerEventHandler",
            "unregisterEventHandler",
            "registerMediaMetadataObserver",
            "unregisterMediaMetadataObserver",
            "getVideoDeviceManager",
            "getAudioDeviceManager",
            "registerAudioSpectrumObserver",
            "unregisterAudioSpectrumObserver",
            "getMediaEngine",
            "getMediaRecorder",
            "registerAudioEncodedFrameObserver",
            "getLocalSpatialAudioEngine",
            "getMusicContentCenter",
            "getH265Transcoder",
        },

    },
    {
        "agora::rtc::IMediaPlayer",
        {
            "registerPlayerSourceObserver",
            "unregisterPlayerSourceObserver",
            "getMediaPlayerId",
            "registerVideoFrameObserver",
            "unregisterVideoFrameObserver",
            "registerMediaPlayerAudioSpectrumObserver",
            "unregisterMediaPlayerAudioSpectrumObserver",
        },
    },
    {
        "agora::media::IMediaEngine",
        {
            "registerAudioFrameObserver",
            "registerVideoFrameObserver",
            "registerVideoEncodedFrameObserver",
        },
    },
    {
        "agora::rtc::MusicCollection",
        {
            "getCount",
            "getTotal",
            "getPage",
            "getPageSize",
            "getPageSize",
            "getMusic",
        },
    },
};

#endif // DART_RENDER_CONFIGS_H_