#ifndef RENAME_MEMBER_FUNCTION_PARAM_TYPE_PARSER_H_
#define RENAME_MEMBER_FUNCTION_PARAM_TYPE_PARSER_H_

#include "terra_parser.hpp"
#include <iterator>
#include <variant>
#include <vector>

// is_builtin_type 用来判断是否可序列化，很重要！！！
class RenameMemberFunctionParamTypeParser : public Parser
{
private:
    std::map<std::string,
             std::map<std::string, std::map<std::string, SimpleType>>>
        member_function_param_ = {
            {
                "IAudioSpectrumObserver",
                {
                    {
                        "onRemoteAudioSpectrum",
                        {
                            {
                                "spectrums",
                                SimpleType{
                                    "agora::media::UserAudioSpectrumInfo",
                                    "const agora::media::UserAudioSpectrumInfo*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IMediaStreamingSourceObserver",
                {
                    {
                        "onMetaData",
                        {
                            {
                                "data",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IRtcEngineEventHandler",
                {
                    {
                        "onWarning",
                        {
                            {
                                "warn",
                                SimpleType{
                                    "agora::WARN_CODE_TYPE",
                                    "agora::WARN_CODE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onError",
                        {
                            {
                                "err",
                                SimpleType{
                                    "agora::ERROR_CODE_TYPE",
                                    "agora::ERROR_CODE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onAudioQuality",
                        {
                            {
                                "quality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onAudioDeviceStateChanged",
                        {
                            {
                                "deviceType",
                                SimpleType{
                                    "agora::rtc::MEDIA_DEVICE_TYPE",
                                    "agora::rtc::MEDIA_DEVICE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                            {
                                "deviceState",
                                SimpleType{
                                    "agora::rtc::MEDIA_DEVICE_STATE_TYPE",
                                    "agora::rtc::MEDIA_DEVICE_STATE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onVideoDeviceStateChanged",
                        {
                            {
                                "deviceType",
                                SimpleType{
                                    "agora::rtc::MEDIA_DEVICE_TYPE",
                                    "agora::rtc::MEDIA_DEVICE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                            {
                                "deviceState",
                                SimpleType{
                                    "agora::rtc::MEDIA_DEVICE_STATE_TYPE",
                                    "agora::rtc::MEDIA_DEVICE_STATE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onMediaDeviceChanged",
                        {
                            {
                                "deviceType",
                                SimpleType{
                                    "agora::rtc::MEDIA_DEVICE_TYPE",
                                    "agora::rtc::MEDIA_DEVICE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onNetworkQuality",
                        {
                            {
                                "txQuality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                            {
                                "rxQuality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onLastmileQuality",
                        {
                            {
                                "quality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onApiCallExecuted",
                        {
                            {
                                "err",
                                SimpleType{
                                    "agora::ERROR_CODE_TYPE",
                                    "agora::ERROR_CODE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onStreamMessage",
                        {
                            {
                                "data",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onStreamMessageError",
                        {
                            {
                                "code",
                                SimpleType{
                                    "agora::ERROR_CODE_TYPE",
                                    "agora::ERROR_CODE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onStreamPublished",
                        {
                            {
                                "error",
                                SimpleType{
                                    "agora::ERROR_CODE_TYPE",
                                    "agora::ERROR_CODE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onChannelMediaRelayStateChanged",
                        {
                            {
                                "state",
                                SimpleType{
                                    "agora::rtc::CHANNEL_MEDIA_RELAY_STATE",
                                    "agora::rtc::CHANNEL_MEDIA_RELAY_STATE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                            {
                                "code",
                                SimpleType{
                                    "agora::rtc::CHANNEL_MEDIA_RELAY_ERROR",
                                    "agora::rtc::CHANNEL_MEDIA_RELAY_ERROR",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onChannelMediaRelayEvent",
                        {
                            {
                                "code",
                                SimpleType{
                                    "agora::rtc::CHANNEL_MEDIA_RELAY_EVENT",
                                    "agora::rtc::CHANNEL_MEDIA_RELAY_EVENT",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onAudioVolumeIndication",
                        {
                            {
                                "speakers",
                                SimpleType{
                                    "agora::rtc::AudioVolumeInfo",
                                    "const agora::rtc::AudioVolumeInfo*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onFacePositionChanged",
                        {
                            {
                                "vecRectangle",
                                SimpleType{
                                    "agora::rtc::Rectangle",
                                    "const agora::rtc::Rectangle*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "vecDistance",
                                SimpleType{
                                    "int",
                                    "const int*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IRtcEngineEventHandlerEx",
                {
                    {
                        "onStreamMessage",
                        {
                            {
                                "data",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onAudioQuality",
                        {
                            {
                                "quality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onStreamMessageError",
                        {
                            {
                                "code",
                                SimpleType{
                                    "agora::ERROR_CODE_TYPE",
                                    "agora::ERROR_CODE_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onAudioVolumeIndication",
                        {
                            {
                                "speakers",
                                SimpleType{
                                    "agora::rtc::AudioVolumeInfo",
                                    "const agora::rtc::AudioVolumeInfo*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "onNetworkQuality",
                        {
                            {
                                "txQuality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                            {
                                "rxQuality",
                                SimpleType{
                                    "agora::rtc::QUALITY_TYPE",
                                    "agora::rtc::QUALITY_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IMediaPlayerSourceObserver",
                {
                    {
                        "onMetaData",
                        {
                            {
                                "data",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IRtcEngine",
                {
                    {
                        "createDataStream",
                        {
                            {
                                "config",
                                SimpleType{
                                    "DataStreamConfig",
                                    "const DataStreamConfig&",
                                    SimpleTypeKind::reference_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "sendStreamMessage",
                        {
                            {
                                "data",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "startScreenCapture",
                        {
                            {
                                "mediaProjectionPermissionResultData",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "setLogFilter",
                        {
                            {
                                "filter",
                                SimpleType{
                                    "agora::commons::LOG_FILTER_TYPE",
                                    "agora::commons::LOG_FILTER_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "enableInEarMonitoring",
                        {
                            {
                                "includeAudioFilters",
                                SimpleType{
                                    "agora::rtc::EAR_MONITORING_FILTER_TYPE",
                                    "agora::rtc::EAR_MONITORING_FILTER_TYPE",
                                    SimpleTypeKind::value_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "queryCodecCapability",
                        {
                            {
                                "codec_info",
                                SimpleType{
                                    "CodecCapInfo",
                                    "CodecCapInfo*",
                                    SimpleTypeKind::array_t,
                                    false,
                                    false,
                                },
                            },
                            {
                                "codecInfo",
                                SimpleType{
                                    "CodecCapInfo",
                                    "CodecCapInfo*",
                                    SimpleTypeKind::array_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "startDirectCdnStreaming",
                        {
                            {
                                "eventHandler",
                                SimpleType{
                                    "IDirectCdnStreamingEventHandler",
                                    "const IDirectCdnStreamingEventHandler*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeAudioBlocklist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeAudioBlacklist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeAudioAllowlist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeAudioWhitelist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeVideoBlocklist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeVideoBlacklist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeVideoAllowlist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeVideoWhitelist",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setHighPriorityUserList",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setAdvancedAudioOptions",
                        {
                            {
                                "options",
                                SimpleType{
                                    "AdvancedAudioOptions",
                                    "const AdvancedAudioOptions&",
                                    SimpleTypeKind::reference_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                },
            },
            {
                "IRtcEngineEx",
                {
                    {
                        "createDataStreamEx",
                        {
                            {
                                "config",
                                SimpleType{
                                    "DataStreamConfig",
                                    "const DataStreamConfig&",
                                    SimpleTypeKind::reference_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "sendStreamMessageEx",
                        {
                            {
                                "data",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeAudioBlocklistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeAudioBlacklistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeAudioAllowlistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeAudioWhitelistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeVideoBlocklistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeVideoBlacklistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    // Renamed since native sdk 4.1.0
                    {
                        "setSubscribeVideoAllowlistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setSubscribeVideoWhitelistEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "setHighPriorityUserListEx",
                        {
                            {
                                "uidList",
                                SimpleType{
                                    "uid_t",
                                    "const uid_t*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                },
            },
            {
                "IMediaEngine",
                {
                    {
                        "pullAudioFrame",
                        {
                            {
                                "frame",
                                SimpleType{
                                    "IAudioFrameObserver::AudioFrame",
                                    "const IAudioFrameObserver::AudioFrame*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "pushAudioFrame",
                        {
                            {
                                "frame",
                                SimpleType{
                                    "IAudioFrameObserver::AudioFrame",
                                    "const IAudioFrameObserver::AudioFrame*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "pushCaptureAudioFrame",
                        {
                            {
                                "frame",
                                SimpleType{
                                    "IAudioFrameObserver::AudioFrame",
                                    "const IAudioFrameObserver::AudioFrame*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "pushReverseAudioFrame",
                        {
                            {
                                "frame",
                                SimpleType{
                                    "IAudioFrameObserver::AudioFrame",
                                    "const IAudioFrameObserver::AudioFrame*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "pushDirectAudioFrame",
                        {
                            {
                                "frame",
                                SimpleType{
                                    "IAudioFrameObserver::AudioFrame",
                                    "const IAudioFrameObserver::AudioFrame*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                    {
                        "pushVideoFrame",
                        {
                            {
                                "frame",
                                SimpleType{
                                    "base::ExternalVideoFrame",
                                    "const base::ExternalVideoFrame*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                },
            },
            {
                "IMediaRecorder",
                {
                    {
                        "setMediaRecorderObserver",
                        {
                            {
                                "callback",
                                SimpleType{
                                    "media::IMediaRecorderObserver",
                                    "const media::IMediaRecorderObserver*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            }
                        }
                    },
                },
            },
            {
                "IBaseSpatialAudioEngine",
                {
                    {
                        "setZones",
                        {
                            {
                                "zones",
                                SimpleType{
                                    "agora::rtc::SpatialAudioZone",
                                    "const agora::rtc::SpatialAudioZone*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                    {
                        "updateSelfPosition",
                        {
                            {
                                "position",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "axisForward",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "axisRight",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "axisUp",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        },
                    },
                    {
                        "updateSelfPositionEx",
                        {
                            {
                                "position",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "axisForward",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "axisRight",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                            {
                                "axisUp",
                                SimpleType{
                                    "float",
                                    "const float*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            }
                        },
                    },
                },
            },
            {
                "IMusicContentCenterEventHandler",
                {
                    {
                        "onMusicChartsResult",
                        {
                            {
                                "result",
                                SimpleType{
                                    "agora::rtc::MusicChartInfo",
                                    "const agora::rtc::MusicChartInfo*",
                                    SimpleTypeKind::array_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IMusicContentCenter",
                {
                    {
                        "getCaches",
                        {
                            {
                                "cacheInfo",
                                SimpleType{
                                    "agora::rtc::MusicCacheInfo",
                                    "agora::rtc::MusicCacheInfo*",
                                    SimpleTypeKind::array_t,
                                    false,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
            {
                "IStreamChannel",
                {
                    {
                        "publishTopicMessage",
                        {
                            {
                                "message",
                                SimpleType{
                                    "uint8_t",
                                    "const uint8_t*",
                                    SimpleTypeKind::pointer_t,
                                    true,
                                    false,
                                },
                            },
                        },
                    },
                },
            },
        };

    std::map<std::string, std::map<std::string, SimpleType>> member_variable_ = {
        {
            "VideoCanvas",
            {
                {
                    "priv",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },
        {
            "ThumbImageBuffer",
            {
                {
                    "buffer",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },
        {
            "ExternalVideoFrame",
            {
                {
                    "buffer",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },
        {
            "AudioFrame",
            {
                {
                    "buffer",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },
        {
            "VideoCompositingLayout",
            {
                {
                    "appData",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },
        {
            "JoinTopicOptions",
            {
                {
                    "meta",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },

        {
            "MessageEvent",
            {
                {
                    "message",
                    SimpleType{
                        "uint8_t",
                        "const uint8_t*",
                        SimpleTypeKind::pointer_t,
                        true,
                        false,
                    },
                },
            },
        },
    };

public:
    bool Parse(const ParseConfig &parse_config,
               ParseResult &parse_result) override
    {
        for (auto &f : parse_result.cxx_files)
        {
            for (auto &node : f.nodes)
            {
                if (std::holds_alternative<Clazz>(node))
                {
                    Clazz &clazz = std::get<Clazz>(node);

                    auto ms = member_function_param_.find(clazz.name);
                    if (ms != member_function_param_.end())
                    {
                        std::map<std::string, std::map<std::string, SimpleType>> &m =
                            ms->second;
                        for (auto &method : clazz.methods)
                        {
                            if (m.find(method.name) != m.end())
                            {
                                std::map<std::string, SimpleType> ps =
                                    m.find(method.name)->second;

                                for (auto &param : method.parameters)
                                {
                                    if (ps.find(param.name) != ps.end())
                                    {
                                        // param.type.name = ps.find(param.name)->second;
                                        param.type = ps.find(param.name)->second;
                                        // param.type.source = param.type.name;
                                    }
                                }
                            }
                        }
                    }
                }

                if (std::holds_alternative<Struct>(node))
                {
                    Struct &structt = std::get<Struct>(node);

                    auto ms = member_variable_.find(structt.name);
                    if (ms != member_variable_.end())
                    {
                        std::map<std::string, SimpleType> &m = ms->second;
                        for (auto &param : structt.member_variables)
                        {
                            if (m.find(param.name) != m.end())
                            {
                                // param.type.name = m.find(param.name)->second;
                                param.type = m.find(param.name)->second;
                                // param.type.source = param.type.name;
                            }
                        }
                    }
                }
            }
        }
    }
};

#endif // RENAME_MEMBER_FUNCTION_PARAM_TYPE_PARSER_H_